import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={inter.className}>
            <div className='w-screen h-screen flex'>
                <nav className='w-1/6 h-full bg-red-500'>SieBar</nav>
                <main className='w-5/6 h-full'>{children}</main>
            </div>
        </body>
    </html>
  )
}