import '../globals.css'
import { Inter } from 'next/font/google'
import SideNavbar from '@/components/Shared/Sidenavbar'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
            <div className='w-screen h-screen flex'>
                <SideNavbar Route='Trainees'/> 
                <main className='w-5/6 h-full bg-white'>{children}</main>
            </div>
        </body>
    </html>
  )
}
